import type {
  LandingConfig,
  LandingSection,
  LandingSectionId,
  LandingTemplate,
  LandingTier,
  SectionBg,
  SectionBlockData,
} from "@/lib/supabase";
import { defaultBlockData, normalizeSeo } from "@/lib/landing-model";

export const DEFAULT_PRICING: LandingTier[] = [
  {
    name: "Starter",
    price: "$0",
    period: "/mo",
    featured: false,
    perks: ["Up to 3 projects", "Community support", "Basic analytics"],
  },
  {
    name: "Pro",
    price: "$29",
    period: "/mo",
    featured: true,
    perks: [
      "Unlimited projects",
      "Priority support",
      "Advanced analytics",
      "Custom domains",
    ],
  },
  {
    name: "Team",
    price: "$99",
    period: "/mo",
    featured: false,
    perks: ["Everything in Pro", "Team workspaces", "SSO & SAML", "Audit logs"],
  },
];

export const DEFAULT_STATS = [
  { value: "10k+", label: "Active users" },
  { value: "99.9%", label: "Uptime" },
  { value: "4.9/5", label: "Avg. rating" },
  { value: "120+", label: "Integrations" },
];

export const DEFAULT_LOGOS = ["Acme", "Globex", "Initech", "Umbra", "Hooli"];

export const DEFAULT_FAQ = [
  {
    q: "Can I cancel anytime?",
    a: "Yes — plans are month-to-month and you can cancel with one click.",
  },
  {
    q: "Do you offer a free trial?",
    a: "Every paid plan starts with a 14-day free trial, no card required.",
  },
  {
    q: "Is my data secure?",
    a: "We encrypt data in transit and at rest, and never sell your information.",
  },
];

function sec(
  id: LandingSectionId,
  uid: string,
  bg: SectionBg = "default",
  data?: SectionBlockData
): LandingSection {
  return { uid, id, visible: true, bg, data: data ?? defaultBlockData(id) };
}

type TemplateBase = Omit<LandingConfig, "seo" | "pages" | "activePageId">;

export function finalizeLanding(
  c: TemplateBase & Partial<Pick<LandingConfig, "seo" | "pages" | "activePageId">>
): LandingConfig {
  const sections = c.sections ?? [];
  const pages = c.pages ?? [{ id: "home", name: "Home", slug: "home", sections }];
  const activePageId = c.activePageId ?? pages[0]?.id ?? "home";
  const activeSections =
    pages.find((p) => p.id === activePageId)?.sections ?? sections;
  return {
    ...c,
    sections: activeSections,
    seo: c.seo ?? normalizeSeo(undefined, c),
    pages,
    activePageId,
  };
}

export const LANDING_TEMPLATES: Record<LandingTemplate, TemplateBase> = {
  saas: {
    template: "saas",
    brandName: "Northwind",
    brandColor: "#6366F1",
    font: "sans",
    radius: 12,
    shadow: "soft",
    mode: "light",
    heroAlign: "center",
    density: "cozy",
    showNav: true,
    showHero: true,
    showHeroVisual: true,
    heroImage: "",
    navLinks: ["Features", "Pricing", "Docs"],
    heroBadge: "New · v2.0 is live",
    heroHeadline: "Launch your product at the speed of thought",
    heroSubtitle:
      "The all-in-one platform to design, ship, and scale beautiful software — no code required.",
    ctaPrimary: "Start free",
    ctaSecondary: "Book a demo",
    ctaHeadline: "Ready to build something great?",
    featuresHeading: "Everything you need to ship",
    features: [
      { title: "Lightning fast", desc: "Ship in minutes with a workflow built for speed." },
      { title: "Secure by default", desc: "Enterprise-grade security baked into every layer." },
      { title: "Scales with you", desc: "From your first user to your millionth, no rewrites." },
    ],
    pricingHeading: "Simple, transparent pricing",
    pricing: DEFAULT_PRICING,
    testimonialQuote:
      "This is hands down the fastest way we've ever shipped a product.",
    testimonialAuthor: "Alex Rivera · CTO, Lumen",
    statsHeading: "Trusted at scale",
    stats: DEFAULT_STATS,
    logosHeading: "Trusted by fast-moving teams",
    logos: DEFAULT_LOGOS,
    faqHeading: "Frequently asked questions",
    faq: DEFAULT_FAQ,
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: true,
    sections: [
      sec("logos", "saas-logos"),
      sec("features", "saas-features"),
      sec("stats", "saas-stats"),
      sec("pricing", "saas-pricing"),
      sec("testimonial", "saas-testimonial"),
      sec("faq", "saas-faq"),
      sec("cta", "saas-cta"),
      sec("footer", "saas-footer"),
    ],
  },
  startup: {
    template: "startup",
    brandName: "Nova",
    brandColor: "#8B5CF6",
    font: "sans",
    radius: 18,
    shadow: "glow",
    mode: "dark",
    heroAlign: "center",
    density: "spacious",
    showNav: true,
    showHero: true,
    showHeroVisual: true,
    heroImage: "",
    navLinks: ["Product", "Features", "Company"],
    heroBadge: "Backed by top founders",
    heroHeadline: "The future of teamwork is finally here",
    heroSubtitle:
      "Nova brings your docs, tasks, and conversations into one beautifully fast workspace.",
    ctaPrimary: "Join the beta",
    ctaSecondary: "Watch video",
    ctaHeadline: "Be the first to try Nova",
    featuresHeading: "Why teams choose Nova",
    features: [
      { title: "All-in-one", desc: "Docs, tasks, and chat finally living in one place." },
      { title: "Real-time sync", desc: "Everyone stays on the same page, instantly." },
      { title: "Built for speed", desc: "Keyboard-first and blazing fast on any device." },
    ],
    pricingHeading: "Plans that grow with your team",
    pricing: DEFAULT_PRICING,
    testimonialQuote: "We replaced four tools with Nova and never looked back.",
    testimonialAuthor: "Priya Shah · Founder, Drift",
    statsHeading: "Loved by growing teams",
    stats: DEFAULT_STATS,
    logosHeading: "Backed by the best",
    logos: DEFAULT_LOGOS,
    faqHeading: "Questions, answered",
    faq: DEFAULT_FAQ,
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: true,
    sections: [
      sec("features", "startup-features"),
      sec("stats", "startup-stats"),
      sec("testimonial", "startup-testimonial"),
      sec("cta", "startup-cta"),
      sec("footer", "startup-footer"),
    ],
  },
  "mobile-app": {
    template: "mobile-app",
    brandName: "Pulse",
    brandColor: "#06B6D4",
    font: "sans",
    radius: 16,
    shadow: "glow",
    mode: "dark",
    heroAlign: "center",
    density: "spacious",
    showNav: true,
    showHero: true,
    showHeroVisual: true,
    heroImage: "",
    navLinks: ["Features", "Reviews", "Download"],
    heroBadge: "4.9★ on the App Store",
    heroHeadline: "Your daily habits, beautifully tracked",
    heroSubtitle:
      "Pulse helps you build routines that stick — with gentle reminders, streaks, and insights that actually motivate.",
    ctaPrimary: "Download free",
    ctaSecondary: "See how it works",
    ctaHeadline: "Start your streak today",
    featuresHeading: "Built for real life",
    features: [
      { title: "Smart reminders", desc: "Nudges that fit your schedule, not the other way around." },
      { title: "Streak insights", desc: "See patterns and celebrate progress without guilt." },
      { title: "Works offline", desc: "Log anywhere — syncs when you're back online." },
    ],
    pricingHeading: "Free to start, premium when ready",
    pricing: [
      {
        name: "Free",
        price: "$0",
        period: "",
        featured: false,
        perks: ["3 habits", "Basic stats", "Daily reminders"],
      },
      {
        name: "Plus",
        price: "$4.99",
        period: "/mo",
        featured: true,
        perks: ["Unlimited habits", "Advanced insights", "Widgets", "Cloud backup"],
      },
      {
        name: "Family",
        price: "$9.99",
        period: "/mo",
        featured: false,
        perks: ["Up to 6 members", "Shared goals", "Everything in Plus"],
      },
    ],
    testimonialQuote: "The only habit app I've kept for more than a month.",
    testimonialAuthor: "Chris Tan · Product designer",
    statsHeading: "Join millions building better days",
    stats: [
      { value: "2M+", label: "Downloads" },
      { value: "4.9", label: "App Store rating" },
      { value: "180", label: "Countries" },
      { value: "12M", label: "Habits completed" },
    ],
    logosHeading: "Featured in",
    logos: ["TechCrunch", "Product Hunt", "The Verge", "Wired", "Forbes"],
    faqHeading: "Common questions",
    faq: [
      { q: "Is Pulse free?", a: "Yes — the core app is free. Plus unlocks advanced insights and unlimited habits." },
      { q: "iOS and Android?", a: "Both, with full feature parity and cross-device sync." },
      { q: "Does it sell my data?", a: "Never. Your habits stay private and encrypted." },
    ],
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: true,
    sections: [
      sec("features", "mobile-app-features"),
      sec("stats", "mobile-app-stats"),
      sec("testimonial", "mobile-app-testimonial"),
      sec("faq", "mobile-app-faq"),
      sec("cta", "mobile-app-cta"),
      sec("footer", "mobile-app-footer"),
    ],
  },
  course: {
    template: "course",
    brandName: "LearnLab",
    brandColor: "#4F46E5",
    font: "sans",
    radius: 10,
    shadow: "soft",
    mode: "light",
    heroAlign: "left",
    density: "cozy",
    showNav: true,
    showHero: true,
    showHeroVisual: true,
    heroImage: "",
    navLinks: ["Curriculum", "Pricing", "FAQ"],
    heroBadge: "New cohort · Starts March 3",
    heroHeadline: "Master modern web development in 8 weeks",
    heroSubtitle:
      "A hands-on course with live sessions, real projects, and mentor feedback — from zero to job-ready portfolio.",
    ctaPrimary: "Enroll now",
    ctaSecondary: "View syllabus",
    ctaHeadline: "Your next chapter starts here",
    featuresHeading: "What you'll learn",
    features: [
      { title: "HTML, CSS & JS", desc: "Solid fundamentals with modern best practices." },
      { title: "React & Next.js", desc: "Build production apps with the tools teams use today." },
      { title: "Ship a capstone", desc: "Deploy a full project for your portfolio and interviews." },
    ],
    pricingHeading: "Choose your path",
    pricing: [
      {
        name: "Self-paced",
        price: "$149",
        period: "",
        featured: false,
        perks: ["Full video library", "Community forum", "Lifetime access"],
      },
      {
        name: "Cohort",
        price: "$499",
        period: "",
        featured: true,
        perks: ["Live weekly sessions", "Code reviews", "Career coaching", "Certificate"],
      },
      {
        name: "Team",
        price: "Custom",
        period: "",
        featured: false,
        perks: ["Bulk seats", "Private Slack", "Custom workshops"],
      },
    ],
    testimonialQuote: "I landed my first dev role two months after finishing LearnLab.",
    testimonialAuthor: "Maya Chen · Frontend developer",
    statsHeading: "Proven outcomes",
    stats: [
      { value: "3,200+", label: "Graduates" },
      { value: "87%", label: "Completion rate" },
      { value: "4.8/5", label: "Student rating" },
      { value: "62%", label: "Career switchers" },
    ],
    logosHeading: "Alumni hired at",
    logos: DEFAULT_LOGOS,
    faqHeading: "Before you enroll",
    faq: [
      { q: "Do I need prior experience?", a: "No — we start from basics and ramp up quickly with guided projects." },
      { q: "What if I miss a live session?", a: "All sessions are recorded and available within 24 hours." },
      { q: "Refund policy?", a: "Full refund within 14 days if the course isn't the right fit." },
    ],
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: true,
    sections: [
      sec("features", "course-features"),
      sec("stats", "course-stats"),
      sec("pricing", "course-pricing"),
      sec("testimonial", "course-testimonial"),
      sec("faq", "course-faq"),
      sec("cta", "course-cta"),
      sec("footer", "course-footer"),
    ],
  },
  agency: {
    template: "agency",
    brandName: "Atlas Studio",
    brandColor: "#F97316",
    font: "serif",
    radius: 4,
    shadow: "sharp",
    mode: "light",
    heroAlign: "left",
    density: "cozy",
    showNav: true,
    showHero: true,
    showHeroVisual: false,
    heroImage: "",
    navLinks: ["Work", "Services", "About"],
    heroBadge: "Award-winning studio",
    heroHeadline: "We craft brands that move people",
    heroSubtitle:
      "A design studio partnering with ambitious teams to build identities, websites, and products.",
    ctaPrimary: "Start a project",
    ctaSecondary: "See our work",
    ctaHeadline: "Let's make something iconic together",
    featuresHeading: "What we do",
    features: [
      { title: "Brand identity", desc: "Logos, systems, and stories that stick." },
      { title: "Web design", desc: "Beautiful, fast sites that convert visitors." },
      { title: "Product design", desc: "Interfaces people genuinely love to use." },
    ],
    pricingHeading: "Engagement options",
    pricing: DEFAULT_PRICING,
    testimonialQuote: "Atlas transformed how the world sees our brand. Pure magic.",
    testimonialAuthor: "Marco Bianchi · CEO, Vela",
    statsHeading: "Our impact",
    stats: DEFAULT_STATS,
    logosHeading: "Clients we've partnered with",
    logos: DEFAULT_LOGOS,
    faqHeading: "Good to know",
    faq: DEFAULT_FAQ,
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: true,
    sections: [
      sec("logos", "agency-logos"),
      sec("features", "agency-features"),
      sec("testimonial", "agency-testimonial"),
      sec("footer", "agency-footer"),
    ],
  },
  consulting: {
    template: "consulting",
    brandName: "Meridian Advisory",
    brandColor: "#0F766E",
    font: "serif",
    radius: 6,
    shadow: "soft",
    mode: "light",
    heroAlign: "left",
    density: "cozy",
    showNav: true,
    showHero: true,
    showHeroVisual: false,
    heroImage: "",
    navLinks: ["Services", "Results", "Contact"],
    heroBadge: "Strategy · Operations · Growth",
    heroHeadline: "Clarity for leaders navigating change",
    heroSubtitle:
      "We partner with executives to sharpen strategy, streamline operations, and unlock sustainable growth.",
    ctaPrimary: "Book a consultation",
    ctaSecondary: "Our approach",
    ctaHeadline: "Let's talk about your next move",
    featuresHeading: "How we help",
    features: [
      { title: "Strategy sprints", desc: "Focused workshops that align teams on priorities in days, not months." },
      { title: "Operational excellence", desc: "Process design that cuts waste and scales what works." },
      { title: "Growth advisory", desc: "Go-to-market plans grounded in data and real customer insight." },
    ],
    pricingHeading: "Engagement models",
    pricing: [
      {
        name: "Discovery",
        price: "$2,500",
        period: "",
        featured: false,
        perks: ["2-week assessment", "Stakeholder interviews", "Priority roadmap"],
      },
      {
        name: "Advisory",
        price: "$8,000",
        period: "/mo",
        featured: true,
        perks: ["Dedicated partner", "Weekly sessions", "Board-ready deliverables"],
      },
      {
        name: "Transformation",
        price: "Custom",
        period: "",
        featured: false,
        perks: ["End-to-end program", "Change management", "Team enablement"],
      },
    ],
    testimonialQuote: "Meridian helped us cut decision cycles in half and hit our revenue target early.",
    testimonialAuthor: "Diane Okonkwo · COO, Northgate",
    statsHeading: "Track record",
    stats: [
      { value: "15 yrs", label: "In business" },
      { value: "200+", label: "Clients served" },
      { value: "$2.1B", label: "Client revenue influenced" },
      { value: "94%", label: "Repeat engagements" },
    ],
    logosHeading: "Trusted by leaders at",
    logos: DEFAULT_LOGOS,
    faqHeading: "Working together",
    faq: DEFAULT_FAQ,
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: true,
    sections: [
      sec("logos", "consulting-logos"),
      sec("features", "consulting-features"),
      sec("stats", "consulting-stats"),
      sec("testimonial", "consulting-testimonial"),
      sec("cta", "consulting-cta"),
      sec("footer", "consulting-footer"),
    ],
  },
  ecommerce: {
    template: "ecommerce",
    brandName: "Bloom & Co",
    brandColor: "#DB2777",
    font: "sans",
    radius: 14,
    shadow: "soft",
    mode: "light",
    heroAlign: "center",
    density: "cozy",
    showNav: true,
    showHero: true,
    showHeroVisual: true,
    heroImage: "",
    navLinks: ["Shop", "Collections", "About"],
    heroBadge: "Spring collection · New arrivals",
    heroHeadline: "Everyday essentials, thoughtfully made",
    heroSubtitle:
      "Small-batch home goods and gifts — designed to last, shipped carbon-neutral to your door.",
    ctaPrimary: "Shop the collection",
    ctaSecondary: "Our story",
    ctaHeadline: "Free shipping on orders over $75",
    featuresHeading: "Why customers love Bloom",
    features: [
      { title: "Ethically sourced", desc: "Materials traced to responsible suppliers we know by name." },
      { title: "Built to last", desc: "Quality you can feel — fewer replacements, less waste." },
      { title: "Easy returns", desc: "30-day hassle-free returns, no questions asked." },
    ],
    pricingHeading: "Membership perks",
    pricing: [
      {
        name: "Guest",
        price: "Free",
        period: "",
        featured: false,
        perks: ["Standard shipping", "Order tracking", "Email support"],
      },
      {
        name: "Bloom Club",
        price: "$9",
        period: "/mo",
        featured: true,
        perks: ["Free shipping always", "Early access drops", "10% off every order"],
      },
      {
        name: "Gift",
        price: "Custom",
        period: "",
        featured: false,
        perks: ["Curated boxes", "Personal note", "Corporate gifting"],
      },
    ],
    testimonialQuote: "The quality blew me away — these are pieces I'll keep for years.",
    testimonialAuthor: "Elena Vasquez · Repeat customer",
    statsHeading: "By the numbers",
    stats: [
      { value: "50k+", label: "Happy customers" },
      { value: "4.8★", label: "Average review" },
      { value: "100%", label: "Carbon-neutral shipping" },
      { value: "48hr", label: "Avg. delivery" },
    ],
    logosHeading: "As seen in",
    logos: ["Vogue", "Domino", "Apartment Therapy", "Goop", "Refinery29"],
    faqHeading: "Shopping FAQ",
    faq: [
      { q: "How long does shipping take?", a: "Most orders arrive within 3–5 business days in the US." },
      { q: "International shipping?", a: "Yes — we ship to 40+ countries with duties calculated at checkout." },
      { q: "Gift wrapping?", a: "Available at checkout for $5 with a handwritten note." },
    ],
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: true,
    sections: [
      sec("features", "ecommerce-features"),
      sec("stats", "ecommerce-stats"),
      sec("testimonial", "ecommerce-testimonial"),
      sec("pricing", "ecommerce-pricing"),
      sec("cta", "ecommerce-cta"),
      sec("footer", "ecommerce-footer"),
    ],
  },
  portfolio: {
    template: "portfolio",
    brandName: "Jordan Lee",
    brandColor: "#10B981",
    font: "serif",
    radius: 8,
    shadow: "soft",
    mode: "dark",
    heroAlign: "left",
    density: "compact",
    showNav: true,
    showHero: true,
    showHeroVisual: false,
    heroImage: "",
    navLinks: ["Work", "About", "Contact"],
    heroBadge: "Available for freelance",
    heroHeadline: "Designer & developer crafting digital products",
    heroSubtitle:
      "I help startups turn rough ideas into polished, usable software people love.",
    ctaPrimary: "Get in touch",
    ctaSecondary: "View résumé",
    ctaHeadline: "Have a project in mind? Let's talk.",
    featuresHeading: "What I do",
    features: [
      { title: "UI / UX design", desc: "Wireframes to pixel-perfect, user-tested flows." },
      { title: "Frontend dev", desc: "Fast, accessible interfaces in React & Next.js." },
      { title: "Brand & identity", desc: "Cohesive visual systems for new ventures." },
    ],
    pricingHeading: "How we can work together",
    pricing: DEFAULT_PRICING,
    testimonialQuote: "Jordan delivered beyond expectations — fast, thoughtful, and reliable.",
    testimonialAuthor: "Sam Okafor · Founder, Tidal",
    statsHeading: "By the numbers",
    stats: DEFAULT_STATS,
    logosHeading: "Worked with",
    logos: DEFAULT_LOGOS,
    faqHeading: "FAQ",
    faq: DEFAULT_FAQ,
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: true,
    sections: [
      sec("features", "portfolio-features"),
      sec("testimonial", "portfolio-testimonial"),
      sec("cta", "portfolio-cta"),
      sec("footer", "portfolio-footer"),
    ],
  },
  photography: {
    template: "photography",
    brandName: "Lens & Light",
    brandColor: "#A8A29E",
    font: "serif",
    radius: 2,
    shadow: "sharp",
    mode: "dark",
    heroAlign: "center",
    density: "spacious",
    showNav: true,
    showHero: true,
    showHeroVisual: true,
    heroImage: "",
    navLinks: ["Portfolio", "Services", "About"],
    heroBadge: "Fine art · Editorial · Weddings",
    heroHeadline: "Stories told in light and shadow",
    heroSubtitle:
      "Award-winning photographer capturing authentic moments for brands, couples, and editorial clients worldwide.",
    ctaPrimary: "View portfolio",
    ctaSecondary: "Book a session",
    ctaHeadline: "Limited dates available this season",
    featuresHeading: "Services",
    features: [
      { title: "Editorial", desc: "Campaign and magazine work with a cinematic eye." },
      { title: "Weddings", desc: "Documentary-style coverage of your day, start to finish." },
      { title: "Brand portraits", desc: "Headshots and lifestyle imagery for teams and founders." },
    ],
    pricingHeading: "Session packages",
    pricing: [
      {
        name: "Portrait",
        price: "$450",
        period: "",
        featured: false,
        perks: ["1-hour session", "15 edited images", "Online gallery"],
      },
      {
        name: "Wedding",
        price: "$3,200",
        period: "",
        featured: true,
        perks: ["Full-day coverage", "Second shooter", "400+ edited photos", "Album credit"],
      },
      {
        name: "Commercial",
        price: "Custom",
        period: "",
        featured: false,
        perks: ["Usage licensing", "Art direction", "Retouching included"],
      },
    ],
    testimonialQuote: "Every frame felt like art — we couldn't have asked for more.",
    testimonialAuthor: "Rachel & Tom · Wedding clients",
    statsHeading: "Experience",
    stats: [
      { value: "12 yrs", label: "Shooting professionally" },
      { value: "800+", label: "Sessions delivered" },
      { value: "18", label: "Countries traveled" },
      { value: "3×", label: "Award winner" },
    ],
    logosHeading: "Published in",
    logos: ["Kinfolk", "Cereal", "Monocle", "Vogue", "National Geographic"],
    faqHeading: "Before booking",
    faq: DEFAULT_FAQ,
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: true,
    sections: [
      sec("features", "photography-features"),
      sec("testimonial", "photography-testimonial"),
      sec("pricing", "photography-pricing"),
      sec("cta", "photography-cta"),
      sec("footer", "photography-footer"),
    ],
  },
  newsletter: {
    template: "newsletter",
    brandName: "Signal Weekly",
    brandColor: "#9333EA",
    font: "sans",
    radius: 20,
    shadow: "soft",
    mode: "light",
    heroAlign: "center",
    density: "compact",
    showNav: true,
    showHero: true,
    showHeroVisual: false,
    heroImage: "",
    navLinks: ["Archive", "About", "Subscribe"],
    heroBadge: "42,000+ readers · Every Tuesday",
    heroHeadline: "The signal in a noisy world",
    heroSubtitle:
      "One thoughtful essay each week on technology, culture, and how to build things that matter — no fluff, no spam.",
    ctaPrimary: "Subscribe free",
    ctaSecondary: "Read latest issue",
    ctaHeadline: "Join 42,000 curious readers",
    featuresHeading: "What you get",
    features: [
      { title: "Deep dives", desc: "Long-form essays you won't find in your feed." },
      { title: "Curated links", desc: "Five reads worth your time, every issue." },
      { title: "No ads ever", desc: "Supported by readers, not sponsors." },
    ],
    pricingHeading: "Support the work",
    pricing: [
      {
        name: "Free",
        price: "$0",
        period: "",
        featured: false,
        perks: ["Weekly newsletter", "Public archive", "Unsubscribe anytime"],
      },
      {
        name: "Member",
        price: "$7",
        period: "/mo",
        featured: true,
        perks: ["Bonus essays", "Community forum", "Early access", "Direct replies"],
      },
      {
        name: "Patron",
        price: "$25",
        period: "/mo",
        featured: false,
        perks: ["Everything in Member", "Quarterly AMA", "Name in credits"],
      },
    ],
    testimonialQuote: "The only newsletter I read start to finish every week.",
    testimonialAuthor: "Nina Patel · Startup founder",
    statsHeading: "Community",
    stats: [
      { value: "42k", label: "Subscribers" },
      { value: "58%", label: "Open rate" },
      { value: "200+", label: "Issues published" },
      { value: "4.9★", label: "Reader rating" },
    ],
    logosHeading: "Readers from",
    logos: DEFAULT_LOGOS,
    faqHeading: "FAQ",
    faq: [
      { q: "How often do you send?", a: "Once a week on Tuesday mornings — that's it." },
      { q: "Can I unsubscribe?", a: "One click, anytime. No hard feelings." },
      { q: "Is my email shared?", a: "Never. We don't sell or share subscriber data." },
    ],
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: true,
    sections: [
      sec("features", "newsletter-features"),
      sec("stats", "newsletter-stats"),
      sec("testimonial", "newsletter-testimonial"),
      sec("cta", "newsletter-cta"),
      sec("footer", "newsletter-footer"),
    ],
  },
  restaurant: {
    template: "restaurant",
    brandName: "Ember Kitchen",
    brandColor: "#C2410C",
    font: "serif",
    radius: 8,
    shadow: "soft",
    mode: "light",
    heroAlign: "left",
    density: "cozy",
    showNav: true,
    showHero: true,
    showHeroVisual: true,
    heroImage: "",
    navLinks: ["Menu", "Story", "Reserve"],
    heroBadge: "Wood-fired · Seasonal · Local",
    heroHeadline: "Fire, flavor, and the warmth of the table",
    heroSubtitle:
      "Neighborhood dining with a open kitchen, regional ingredients, and a wine list curated for every course.",
    ctaPrimary: "Reserve a table",
    ctaSecondary: "View menu",
    ctaHeadline: "Book your evening at Ember",
    featuresHeading: "Highlights from the kitchen",
    features: [
      { title: "Wood-fired mains", desc: "Steaks, fish, and vegetables from our custom hearth." },
      { title: "Seasonal menu", desc: "Rotating dishes built around local farms and purveyors." },
      { title: "Private dining", desc: "Intimate rooms for celebrations, tastings, and events." },
    ],
    pricingHeading: "Tasting experiences",
    pricing: [
      {
        name: "À la carte",
        price: "Varies",
        period: "",
        featured: false,
        perks: ["Full dinner menu", "Walk-ins welcome", "Bar seating"],
      },
      {
        name: "Chef's table",
        price: "$95",
        period: "/person",
        featured: true,
        perks: ["5-course menu", "Wine pairings", "Kitchen view", "Reservation required"],
      },
      {
        name: "Private event",
        price: "Custom",
        period: "",
        featured: false,
        perks: ["Custom menu", "Dedicated staff", "Up to 24 guests"],
      },
    ],
    testimonialQuote: "The best meal we've had in years — every dish was unforgettable.",
    testimonialAuthor: "James & Olivia · OpenTable review",
    statsHeading: "Our kitchen",
    stats: [
      { value: "2018", label: "Est. year" },
      { value: "4.8★", label: "Google rating" },
      { value: "12", label: "Local farm partners" },
      { value: "85", label: "Seats" },
    ],
    logosHeading: "Featured in",
    logos: ["Eater", "Bon Appétit", "Infatuation", "Timeout", "Michelin Guide"],
    faqHeading: "Good to know",
    faq: [
      { q: "Do you take walk-ins?", a: "Yes for bar and patio — reservations recommended for dining room." },
      { q: "Dietary restrictions?", a: "We accommodate vegetarian, vegan, and gluten-free with advance notice." },
      { q: "Parking?", a: "Validated parking in the lot behind the restaurant on weekdays." },
    ],
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: true,
    sections: [
      sec("features", "restaurant-features"),
      sec("stats", "restaurant-stats"),
      sec("testimonial", "restaurant-testimonial"),
      sec("cta", "restaurant-cta"),
      sec("footer", "restaurant-footer"),
    ],
  },
  realestate: {
    template: "realestate",
    brandName: "Harbor Homes",
    brandColor: "#1E40AF",
    font: "sans",
    radius: 10,
    shadow: "soft",
    mode: "light",
    heroAlign: "left",
    density: "cozy",
    showNav: true,
    showHero: true,
    showHeroVisual: true,
    heroImage: "",
    navLinks: ["Listings", "Services", "About"],
    heroBadge: "Top 1% agent · Coastal specialist",
    heroHeadline: "Find your place by the water",
    heroSubtitle:
      "Luxury and lifestyle homes along the coast — expert guidance from search to closing and beyond.",
    ctaPrimary: "Browse listings",
    ctaSecondary: "Schedule a call",
    ctaHeadline: "Let's find your next home",
    featuresHeading: "Why work with Harbor",
    features: [
      { title: "Local expertise", desc: "20 years navigating coastal markets and off-market gems." },
      { title: "White-glove service", desc: "Staging, photography, and negotiation handled end to end." },
      { title: "Investor network", desc: "Connections for financing, renovation, and property management." },
    ],
    pricingHeading: "Service tiers",
    pricing: [
      {
        name: "Buyer",
        price: "Free",
        period: "",
        featured: false,
        perks: ["Dedicated search", "Offer strategy", "Closing support"],
      },
      {
        name: "Seller",
        price: "2.5%",
        period: " commission",
        featured: true,
        perks: ["Professional staging", "Premium photography", "Multi-channel marketing"],
      },
      {
        name: "Luxury",
        price: "Custom",
        period: "",
        featured: false,
        perks: ["Private showings", "Global buyer network", "Concierge relocation"],
      },
    ],
    testimonialQuote: "Sold our home in 9 days above asking — couldn't recommend them more.",
    testimonialAuthor: "The Morrison family · Sellers",
    statsHeading: "Results that speak",
    stats: [
      { value: "$240M+", label: "Volume sold" },
      { value: "14 days", label: "Avg. days on market" },
      { value: "98%", label: "List-to-sale ratio" },
      { value: "500+", label: "Families served" },
    ],
    logosHeading: "Affiliated with",
    logos: ["Compass", "Sotheby's", "Christie's", "Redfin", "Zillow Premier"],
    faqHeading: "Buyer & seller FAQ",
    faq: DEFAULT_FAQ,
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: true,
    sections: [
      sec("features", "realestate-features"),
      sec("stats", "realestate-stats"),
      sec("testimonial", "realestate-testimonial"),
      sec("cta", "realestate-cta"),
      sec("footer", "realestate-footer"),
    ],
  },
  fitness: {
    template: "fitness",
    brandName: "Forge Athletics",
    brandColor: "#DC2626",
    font: "sans",
    radius: 6,
    shadow: "glow",
    mode: "dark",
    heroAlign: "center",
    density: "spacious",
    showNav: true,
    showHero: true,
    showHeroVisual: true,
    heroImage: "",
    navLinks: ["Classes", "Pricing", "Join"],
    heroBadge: "Open 24/7 · Downtown location",
    heroHeadline: "Stronger every rep, every day",
    heroSubtitle:
      "Premium gym with expert coaches, small-group classes, and equipment that matches your ambition.",
    ctaPrimary: "Start free trial",
    ctaSecondary: "Class schedule",
    ctaHeadline: "Your first week is on us",
    featuresHeading: "What's included",
    features: [
      { title: "Expert coaching", desc: "Certified trainers for lifting, HIIT, and mobility." },
      { title: "Small-group classes", desc: "Limited spots so you get attention, not a crowd." },
      { title: "Recovery zone", desc: "Sauna, cold plunge, and stretch area post-workout." },
    ],
    pricingHeading: "Membership options",
    pricing: [
      {
        name: "Basic",
        price: "$49",
        period: "/mo",
        featured: false,
        perks: ["Gym access", "Locker room", "App workouts"],
      },
      {
        name: "Unlimited",
        price: "$89",
        period: "/mo",
        featured: true,
        perks: ["All classes", "Guest passes", "Recovery zone", "Nutrition consult"],
      },
      {
        name: "Personal",
        price: "$199",
        period: "/mo",
        featured: false,
        perks: ["4 PT sessions", "Custom program", "Everything in Unlimited"],
      },
    ],
    testimonialQuote: "Forge changed how I train — stronger, healthier, and actually enjoying the gym.",
    testimonialAuthor: "Marcus Webb · Member since 2022",
    statsHeading: "The Forge community",
    stats: [
      { value: "2,400", label: "Active members" },
      { value: "45+", label: "Weekly classes" },
      { value: "15", label: "Expert coaches" },
      { value: "4.9★", label: "Member rating" },
    ],
    logosHeading: "Partners",
    logos: DEFAULT_LOGOS,
    faqHeading: "Membership FAQ",
    faq: [
      { q: "Free trial?", a: "7 days full access — no card required to start." },
      { q: "Cancel anytime?", a: "Month-to-month plans with 30-day notice." },
      { q: "Beginner friendly?", a: "Absolutely — coaches scale every workout to your level." },
    ],
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: true,
    sections: [
      sec("features", "fitness-features"),
      sec("pricing", "fitness-pricing"),
      sec("stats", "fitness-stats"),
      sec("testimonial", "fitness-testimonial"),
      sec("cta", "fitness-cta"),
      sec("footer", "fitness-footer"),
    ],
  },
  event: {
    template: "event",
    brandName: "SummitConf",
    brandColor: "#0284C7",
    font: "sans",
    radius: 12,
    shadow: "soft",
    mode: "light",
    heroAlign: "center",
    density: "cozy",
    showNav: true,
    showHero: true,
    showHeroVisual: true,
    heroImage: "",
    navLinks: ["Speakers", "Schedule", "Tickets"],
    heroBadge: "Oct 14–16 · San Francisco",
    heroHeadline: "Where builders meet the future",
    heroSubtitle:
      "Three days of keynotes, workshops, and hallway conversations with 2,000+ product leaders, engineers, and founders.",
    ctaPrimary: "Get tickets",
    ctaSecondary: "View speakers",
    ctaHeadline: "Early bird ends Friday — save 30%",
    featuresHeading: "Conference tracks",
    features: [
      { title: "Product & design", desc: "Ship faster with talks from teams at top product companies." },
      { title: "Engineering", desc: "Architecture, AI, and infrastructure from practitioners." },
      { title: "Leadership", desc: "Scaling teams, culture, and strategy for growing orgs." },
    ],
    pricingHeading: "Ticket options",
    pricing: [
      {
        name: "Community",
        price: "$199",
        period: "",
        featured: false,
        perks: ["Main stage access", "Expo hall", "Recordings (30 days)"],
      },
      {
        name: "Pro",
        price: "$499",
        period: "",
        featured: true,
        perks: ["All workshops", "Speaker meetups", "Lifetime recordings", "Lunch included"],
      },
      {
        name: "Team",
        price: "$399",
        period: "/seat",
        featured: false,
        perks: ["5+ seats", "Group discount", "Dedicated lounge", "Invoice billing"],
      },
    ],
    testimonialQuote: "The best conference I've attended — every talk was actionable.",
    testimonialAuthor: "Kevin Liu · VP Engineering, Scale",
    statsHeading: "Summit by the numbers",
    stats: [
      { value: "2,000+", label: "Attendees" },
      { value: "80+", label: "Speakers" },
      { value: "3", label: "Days" },
      { value: "40", label: "Countries represented" },
    ],
    logosHeading: "Past sponsors",
    logos: DEFAULT_LOGOS,
    faqHeading: "Attendee FAQ",
    faq: [
      { q: "Refund policy?", a: "Full refund up to 30 days before the event." },
      { q: "Virtual option?", a: "Pro tickets include livestream and lifetime recordings." },
      { q: "Student discounts?", a: "50% off Community tickets with valid .edu email." },
    ],
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: true,
    sections: [
      sec("stats", "event-stats"),
      sec("features", "event-features"),
      sec("pricing", "event-pricing"),
      sec("testimonial", "event-testimonial"),
      sec("faq", "event-faq"),
      sec("cta", "event-cta"),
      sec("footer", "event-footer"),
    ],
  },
  wedding: {
    template: "wedding",
    brandName: "Forever & Co",
    brandColor: "#E11D48",
    font: "serif",
    radius: 16,
    shadow: "soft",
    mode: "light",
    heroAlign: "center",
    density: "spacious",
    showNav: true,
    showHero: true,
    showHeroVisual: true,
    heroImage: "",
    navLinks: ["Services", "Gallery", "Inquire"],
    heroBadge: "Full-service wedding planning",
    heroHeadline: "Your love story, beautifully orchestrated",
    heroSubtitle:
      "From intimate gatherings to grand celebrations — we design and coordinate weddings that feel unmistakably you.",
    ctaPrimary: "Schedule a consult",
    ctaSecondary: "View our work",
    ctaHeadline: "Let's plan something unforgettable",
    featuresHeading: "How we help",
    features: [
      { title: "Full planning", desc: "Vendor curation, timeline, and day-of coordination handled." },
      { title: "Design & styling", desc: "Floral, décor, and aesthetic direction from concept to install." },
      { title: "Destination weddings", desc: "Logistics and local partnerships wherever you say \"I do.\"" },
    ],
    pricingHeading: "Planning packages",
    pricing: [
      {
        name: "Month-of",
        price: "$2,500",
        period: "",
        featured: false,
        perks: ["Final month coordination", "Vendor confirmations", "Day-of team"],
      },
      {
        name: "Partial",
        price: "$5,500",
        period: "",
        featured: true,
        perks: ["Design consults", "Vendor management", "Rehearsal + day-of", "Unlimited email support"],
      },
      {
        name: "Full service",
        price: "$12,000",
        period: "",
        featured: false,
        perks: ["Everything in Partial", "Budget management", "Guest logistics", "Honeymoon planning"],
      },
    ],
    testimonialQuote: "They made our dream wedding feel effortless — we actually enjoyed the day.",
    testimonialAuthor: "Amanda & David · June 2025",
    statsHeading: "Celebrations crafted",
    stats: [
      { value: "350+", label: "Weddings planned" },
      { value: "12 yrs", label: "Experience" },
      { value: "100%", label: "On-time ceremonies" },
      { value: "5.0★", label: "Client rating" },
    ],
    logosHeading: "Featured vendors we love",
    logos: ["Anthropologie", "West Elm", "Terrain", "BHLDN", "Minted"],
    faqHeading: "Planning FAQ",
    faq: [
      { q: "How far in advance to book?", a: "We recommend 12–18 months for peak season dates." },
      { q: "Destination weddings?", a: "Yes — we've planned celebrations in 15 countries." },
      { q: "Minimum budget?", a: "We work with weddings starting at $30k total event budget." },
    ],
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: true,
    sections: [
      sec("features", "wedding-features"),
      sec("testimonial", "wedding-testimonial"),
      sec("pricing", "wedding-pricing"),
      sec("faq", "wedding-faq"),
      sec("cta", "wedding-cta"),
      sec("footer", "wedding-footer"),
    ],
  },
  nonprofit: {
    template: "nonprofit",
    brandName: "HopeForward",
    brandColor: "#059669",
    font: "sans",
    radius: 10,
    shadow: "soft",
    mode: "light",
    heroAlign: "center",
    density: "cozy",
    showNav: true,
    showHero: true,
    showHeroVisual: true,
    heroImage: "",
    navLinks: ["Mission", "Programs", "Donate"],
    heroBadge: "501(c)(3) · 98% to programs",
    heroHeadline: "Clean water changes everything",
    heroSubtitle:
      "HopeForward builds sustainable wells and sanitation systems in communities that need them most — with local partners, not handouts.",
    ctaPrimary: "Donate now",
    ctaSecondary: "Our impact",
    ctaHeadline: "$25 provides clean water for one person for a year",
    featuresHeading: "Our programs",
    features: [
      { title: "Well construction", desc: "Community-owned wells built to last decades, not years." },
      { title: "Hygiene education", desc: "Local trainers teaching sanitation practices that save lives." },
      { title: "Maintenance funds", desc: "Revenue models that keep systems running long after we leave." },
    ],
    pricingHeading: "Ways to give",
    pricing: [
      {
        name: "One-time",
        price: "$25+",
        period: "",
        featured: false,
        perks: ["Tax-deductible receipt", "Impact report", "Thank-you note"],
      },
      {
        name: "Monthly",
        price: "$15",
        period: "/mo",
        featured: true,
        perks: ["Sustaining partner badge", "Quarterly updates", "Annual impact video"],
      },
      {
        name: "Legacy",
        price: "Custom",
        period: "",
        featured: false,
        perks: ["Planned giving support", "Named well option", "Family briefing"],
      },
    ],
    testimonialQuote: "I've seen the wells HopeForward builds — they transform entire villages.",
    testimonialAuthor: "Dr. Helen Park · Field partner, Kenya",
    statsHeading: "Impact to date",
    stats: [
      { value: "1.2M", label: "People served" },
      { value: "340", label: "Wells built" },
      { value: "12", label: "Countries" },
      { value: "98%", label: "To programs" },
    ],
    logosHeading: "Recognized by",
    logos: ["Charity Navigator", "GuideStar", "UN Water", "GiveWell", "Fast Company"],
    faqHeading: "Donor FAQ",
    faq: [
      { q: "Where does my donation go?", a: "98% funds programs — wells, training, and maintenance." },
      { q: "Tax deductible?", a: "Yes — we're a registered 501(c)(3). Receipts sent immediately." },
      { q: "Can I visit a project?", a: "Annual donor trips available — email us for the next delegation." },
    ],
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: true,
    sections: [
      sec("stats", "nonprofit-stats"),
      sec("features", "nonprofit-features"),
      sec("testimonial", "nonprofit-testimonial"),
      sec("cta", "nonprofit-cta"),
      sec("footer", "nonprofit-footer"),
    ],
  },
  scratch: {
    template: "scratch",
    brandName: "Your Brand",
    brandColor: "#6366F1",
    font: "sans",
    radius: 10,
    shadow: "soft",
    mode: "light",
    heroAlign: "center",
    density: "cozy",
    showNav: false,
    showHero: false,
    showHeroVisual: false,
    heroImage: "",
    navLinks: ["Home", "About", "Contact"],
    heroBadge: "",
    heroHeadline: "Your headline goes here",
    heroSubtitle: "Add a short, punchy subtitle that explains what you do.",
    ctaPrimary: "Get started",
    ctaSecondary: "",
    ctaHeadline: "Ready to get started?",
    featuresHeading: "Everything you need",
    features: [
      { title: "Feature one", desc: "Describe this feature." },
      { title: "Feature two", desc: "Describe this feature." },
      { title: "Feature three", desc: "Describe this feature." },
    ],
    statsHeading: "By the numbers",
    stats: DEFAULT_STATS,
    logosHeading: "Trusted by teams everywhere",
    logos: DEFAULT_LOGOS,
    pricingHeading: "Simple, transparent pricing",
    pricing: DEFAULT_PRICING,
    testimonialQuote: "Add a glowing quote from a happy customer here.",
    testimonialAuthor: "Customer name · Role, Company",
    faqHeading: "Frequently asked questions",
    faq: DEFAULT_FAQ,
    featureColumns: 3,
    statsColumns: 4,
    showSecondaryCta: false,
    sections: [],
  },
};
